ALTER TABLE "Patient" ADD COLUMN "search_text" TEXT NOT NULL DEFAULT '';
ALTER TABLE "VlkSession" ADD COLUMN "search_text" TEXT NOT NULL DEFAULT '';
ALTER TABLE "VlkSession" ADD COLUMN "creation_hash" TEXT NOT NULL DEFAULT '';
CREATE TABLE "LoginThrottle" ("key" TEXT NOT NULL PRIMARY KEY,"failures" INTEGER NOT NULL DEFAULT 0,"window_start" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"blocked_until" DATETIME);
