// AUTO-GENERATED by `npm run import:google-places`.
// Empty by default so the app builds without Google credentials.
// External Google Places candidates are review inputs, not public launch data.
import type { GooglePlaceCandidate } from "@/lib/types";

export const GOOGLE_PLACES: GooglePlaceCandidate[] = [];
