/**
 * Реєстр офіційних пояснень: кожна стаття лежить в окремому модулі, тому
 * клієнт завантажує дослівний текст лише для відкритої статті.
 */
import type { ArticleExplanation } from "./types.ts";

export type ExplanationMeta = {
  status: ArticleExplanation["status"];
  anchor: string | null;
  /** Кількість дослівних фрагментів — показується до завантаження тексту. */
  paragraphs: number;
};

export const EXPLANATION_LOADERS: Record<string, () => Promise<{ EXPLANATION: ArticleExplanation }>> = {
  "1": () => import("./article-1.ts"),
  "2": () => import("./article-2.ts"),
  "3": () => import("./article-3.ts"),
  "4": () => import("./article-4.ts"),
  "5": () => import("./article-5.ts"),
  "6": () => import("./article-6.ts"),
  "7": () => import("./article-7.ts"),
  "8": () => import("./article-8.ts"),
  "9": () => import("./article-9.ts"),
  "10": () => import("./article-10.ts"),
  "11": () => import("./article-11.ts"),
  "12": () => import("./article-12.ts"),
  "13": () => import("./article-13.ts"),
  "14": () => import("./article-14.ts"),
  "15": () => import("./article-15.ts"),
  "16": () => import("./article-16.ts"),
  "17": () => import("./article-17.ts"),
  "18": () => import("./article-18.ts"),
  "19": () => import("./article-19.ts"),
  "20": () => import("./article-20.ts"),
  "21": () => import("./article-21.ts"),
  "22": () => import("./article-22.ts"),
  "23": () => import("./article-23.ts"),
  "24": () => import("./article-24.ts"),
  "25": () => import("./article-25.ts"),
  "26": () => import("./article-26.ts"),
  "27": () => import("./article-27.ts"),
  "28": () => import("./article-28.ts"),
  "29": () => import("./article-29.ts"),
  "30": () => import("./article-30.ts"),
  "31": () => import("./article-31.ts"),
  "32": () => import("./article-32.ts"),
  "33": () => import("./article-33.ts"),
  "34": () => import("./article-34.ts"),
  "35": () => import("./article-35.ts"),
  "36": () => import("./article-36.ts"),
  "37": () => import("./article-37.ts"),
  "38": () => import("./article-38.ts"),
  "39": () => import("./article-39.ts"),
  "40": () => import("./article-40.ts"),
  "41": () => import("./article-41.ts"),
  "42": () => import("./article-42.ts"),
  "43": () => import("./article-43.ts"),
  "44": () => import("./article-44.ts"),
  "45": () => import("./article-45.ts"),
  "46": () => import("./article-46.ts"),
  "47": () => import("./article-47.ts"),
  "48": () => import("./article-48.ts"),
  "49": () => import("./article-49.ts"),
  "50": () => import("./article-50.ts"),
  "51": () => import("./article-51.ts"),
  "52": () => import("./article-52.ts"),
  "53": () => import("./article-53.ts"),
  "54": () => import("./article-54.ts"),
  "55": () => import("./article-55.ts"),
  "56": () => import("./article-56.ts"),
  "57": () => import("./article-57.ts"),
  "58": () => import("./article-58.ts"),
  "59": () => import("./article-59.ts"),
  "60": () => import("./article-60.ts"),
  "61": () => import("./article-61.ts"),
  "62": () => import("./article-62.ts"),
  "63": () => import("./article-63.ts"),
  "64": () => import("./article-64.ts"),
  "65": () => import("./article-65.ts"),
  "66": () => import("./article-66.ts"),
  "67": () => import("./article-67.ts"),
  "68": () => import("./article-68.ts"),
  "69": () => import("./article-69.ts"),
  "70": () => import("./article-70.ts"),
  "71": () => import("./article-71.ts"),
  "72": () => import("./article-72.ts"),
  "73": () => import("./article-73.ts"),
  "74": () => import("./article-74.ts"),
  "75": () => import("./article-75.ts"),
  "76": () => import("./article-76.ts"),
  "77": () => import("./article-77.ts"),
  "78": () => import("./article-78.ts"),
  "79": () => import("./article-79.ts"),
  "80": () => import("./article-80.ts"),
  "81": () => import("./article-81.ts"),
  "82": () => import("./article-82.ts"),
  "83": () => import("./article-83.ts"),
  "84": () => import("./article-84.ts"),
  "85": () => import("./article-85.ts"),
  "86": () => import("./article-86.ts"),
  "87": () => import("./article-87.ts"),
};

export const EXPLANATION_META: Record<string, ExplanationMeta> = {
  "1": { status: "official", anchor: "n5980", paragraphs: 8 },
  "2": { status: "official", anchor: "n7476", paragraphs: 2 },
  "3": { status: "official", anchor: "n6036", paragraphs: 3 },
  "4": { status: "official", anchor: "n6039", paragraphs: 14 },
  "5": { status: "official", anchor: "n6053", paragraphs: 17 },
  "6": { status: "official", anchor: "n6070", paragraphs: 1 },
  "7": { status: "official", anchor: "n6071", paragraphs: 5 },
  "8": { status: "official", anchor: "n6076", paragraphs: 19 },
  "9": { status: "official", anchor: "n6095", paragraphs: 15 },
  "10": { status: "official", anchor: "n6110", paragraphs: 40 },
  "11": { status: "official", anchor: "n6150", paragraphs: 4 },
  "12": { status: "official", anchor: "n6154", paragraphs: 43 },
  "13": { status: "official", anchor: "n6197", paragraphs: 248 },
  "14": { status: "official", anchor: "n6242", paragraphs: 6 },
  "15": { status: "official", anchor: "n6248", paragraphs: 8 },
  "16": { status: "official", anchor: "n6253", paragraphs: 4 },
  "17": { status: "official", anchor: "n6257", paragraphs: 8 },
  "18": { status: "official", anchor: "n6262", paragraphs: 4 },
  "19": { status: "official", anchor: "n6266", paragraphs: 4 },
  "20": { status: "official", anchor: "n6270", paragraphs: 9 },
  "21": { status: "official", anchor: "n6279", paragraphs: 4 },
  "22": { status: "official", anchor: "n6283", paragraphs: 12 },
  "23": { status: "official", anchor: "n6295", paragraphs: 6 },
  "24": { status: "official", anchor: "n6302", paragraphs: 7 },
  "25": { status: "official", anchor: "n6309", paragraphs: 20 },
  "26": { status: "official", anchor: "n6329", paragraphs: 29 },
  "27": { status: "official", anchor: "n6357", paragraphs: 2 },
  "28": { status: "official", anchor: "n6359", paragraphs: 1 },
  "29": { status: "official", anchor: "n6360", paragraphs: 4 },
  "30": { status: "official", anchor: "n6364", paragraphs: 2 },
  "31": { status: "official", anchor: "n6366", paragraphs: 5 },
  "32": { status: "official", anchor: "n6371", paragraphs: 2 },
  "33": { status: "official", anchor: "n6373", paragraphs: 1 },
  "34": { status: "official", anchor: "n6374", paragraphs: 5 },
  "35": { status: "official", anchor: "n6379", paragraphs: 37 },
  "36": { status: "official", anchor: "n6405", paragraphs: 48 },
  "37": { status: "official", anchor: "n6422", paragraphs: 2 },
  "38": { status: "official", anchor: "n6424", paragraphs: 320 },
  "39": { status: "official", anchor: "n6523", paragraphs: 61 },
  "40": { status: "official", anchor: "n6556", paragraphs: 75 },
  "41": { status: "official", anchor: "n6610", paragraphs: 17 },
  "42": { status: "official", anchor: "n6623", paragraphs: 34 },
  "43": { status: "official", anchor: "n6647", paragraphs: 1 },
  "44": { status: "official", anchor: "n6648", paragraphs: 5 },
  "45": { status: "official", anchor: "n6653", paragraphs: 15 },
  "46": { status: "official", anchor: "n6668", paragraphs: 52 },
  "47": { status: "official", anchor: "n6683", paragraphs: 19 },
  "48": { status: "official", anchor: "n6702", paragraphs: 3 },
  "49": { status: "official", anchor: "n6705", paragraphs: 1 },
  "50": { status: "official", anchor: "n6706", paragraphs: 1 },
  "51": { status: "official", anchor: "n6710", paragraphs: 15 },
  "52": { status: "official", anchor: "n6725", paragraphs: 32 },
  "53": { status: "official", anchor: "n6757", paragraphs: 20 },
  "54": { status: "official", anchor: "n6777", paragraphs: 21 },
  "55": { status: "official", anchor: "n6798", paragraphs: 15 },
  "56": { status: "official", anchor: "n6812", paragraphs: 4 },
  "57": { status: "official", anchor: "n6816", paragraphs: 5 },
  "58": { status: "official", anchor: "n6821", paragraphs: 4 },
  "59": { status: "official", anchor: "n6825", paragraphs: 3 },
  "60": { status: "official", anchor: "n6828", paragraphs: 8 },
  "61": { status: "official", anchor: "n6836", paragraphs: 142 },
  "62": { status: "official", anchor: "n6869", paragraphs: 57 },
  "63": { status: "official", anchor: "n6909", paragraphs: 2 },
  "64": { status: "official", anchor: "n6911", paragraphs: 87 },
  "65": { status: "official", anchor: "n6941", paragraphs: 3 },
  "66": { status: "official", anchor: "n6944", paragraphs: 71 },
  "67": { status: "official", anchor: "n6964", paragraphs: 27 },
  "68": { status: "official", anchor: "n6991", paragraphs: 14 },
  "69": { status: "official", anchor: "n7005", paragraphs: 11 },
  "70": { status: "official", anchor: "n7016", paragraphs: 4 },
  "71": { status: "official", anchor: "n7020", paragraphs: 20 },
  "72": { status: "official", anchor: "n7040", paragraphs: 4 },
  "73": { status: "official", anchor: "n7044", paragraphs: 4 },
  "74": { status: "official", anchor: "n7048", paragraphs: 42 },
  "75": { status: "official", anchor: "n7089", paragraphs: 44 },
  "76": { status: "official", anchor: "n7133", paragraphs: 26 },
  "77": { status: "official", anchor: "n7157", paragraphs: 28 },
  "78": { status: "official", anchor: "n7183", paragraphs: 20 },
  "79": { status: "official", anchor: "n7203", paragraphs: 39 },
  "80": { status: "official", anchor: "n7242", paragraphs: 10 },
  "81": { status: "official", anchor: "n7252", paragraphs: 9 },
  "82": { status: "official", anchor: "n7261", paragraphs: 3 },
  "83": { status: "official", anchor: "n7264", paragraphs: 7 },
  "84": { status: "official", anchor: "n7271", paragraphs: 3 },
  "85": { status: "official", anchor: "n7274", paragraphs: 8 },
  "86": { status: "official", anchor: "n7282", paragraphs: 4 },
  "87": { status: "absent", anchor: null, paragraphs: 0 },
};
